#pragma once

#include <string>
#include <vector>

// write pnts generated by entwine to tileset json file
struct StSinglePnts {
    unsigned nDepth, x, y, z;
    float vBox[12] = {0};
    std::string sFileName;

    bool operator < (const StSinglePnts& a) {
        if (nDepth == a.nDepth) {
            if (x == a.x) {
                if (y == a.y) return z <= a.z;
                return y < a.y;
            } 
            return x < a.x;
        }

        if (nDepth > a.nDepth) {
            unsigned nDepthParent = nDepth;
            unsigned nXParent = x, nYParent = y, nZParent = z;
            while (nDepthParent > a.nDepth) {
                nDepthParent--;
                nXParent >>= 1;
                nYParent >>= 1;
                nZParent >>= 1;
            }
            if (nXParent == a.x) {
                if (nYParent == a.y) return nZParent < a.z;
                return nYParent < a.y;
            }
            return nXParent < a.x;
        } else {
            unsigned nDepthParent = a.nDepth;
            unsigned nXParent = a.x, nYParent = a.y, nZParent = a.z;
            while (nDepthParent > nDepth) {
                nDepthParent--;
                nXParent >>= 1;
                nYParent >>= 1;
                nZParent >>= 1;
            }
            if (nXParent == x) {
                if (nYParent == y) return z <= nZParent;
                return y < nYParent;
            }
            return x < nZParent;
        }
    }
    StSinglePnts(const std::string& _sFileName, unsigned _nDepth, unsigned _x, unsigned _y, unsigned _z) 
        : sFileName(_sFileName), nDepth(_nDepth), x(_x), y(_y), z(_z) {}

    bool isParent(const StSinglePnts& stParent) const {
        if (nDepth <= stParent.nDepth) return false;
        unsigned nDepthParent = nDepth;
        unsigned nXParent = x;
        unsigned nYParent = y;
        unsigned nZParent = z;
        while (nDepthParent > stParent.nDepth) {
            nDepthParent--;
            nXParent >>= 1;
            nYParent >>= 1;
            nZParent >>= 1;
        }
        return ((nXParent == stParent.x) && (nYParent == stParent.y) && (nZParent == stParent.z));
    }
    bool isChild(const StSinglePnts& stChild) const {
        if (nDepth >= stChild.nDepth) return false;
        unsigned nDepthParent = stChild.nDepth;
        unsigned nXParent = stChild.x;
        unsigned nYParent = stChild.y;
        unsigned nZParent = stChild.z;
        while (nDepthParent > nDepth) {
            nDepthParent--;
            nXParent >>= 1;
            nYParent >>= 1;
            nZParent >>= 1;
        }
        return ((nXParent == x) && (nYParent == y) && (nZParent == z));
    }
};

class JsonManager {
public:
    static JsonManager* getInstance();
    ~JsonManager();

    bool parseRequest(const std::string& sRequestBody);
    bool writeTilesetJson(std::vector<StSinglePnts> vPnts, std::array<double, 16> transform, float vBox[], const std::string &sOutFileName, float fRootGeometryError = 32.f);

private:
    JsonManager();

    static std::string getFileCreateTime(const std::string& sFileName);

private:
    static JsonManager* m_pInstance;

};